openapi: 3.0.0
info:
  title: eBay Account Advertising_eligibility Deal_item API
  description: The <b>Account API</b> gives sellers the ability to configure their eBay seller accounts, including the seller's policies (eBay business policies and seller-defined custom policies), opt in and out of eBay seller programs, configure sales tax tables, and get account information.  <br><br>For details on the availability of the methods in this API, see <a href="/api-docs/sell/account/overview.html#requirements">Account API requirements and restrictions</a>.
  contact:
    name: eBay Inc,
  license:
    name: eBay API License Agreement
    url: https://go.developer.ebay.com/api-license-agreement
  version: v1.9.2
servers:
- url: https://api.ebay.com{basePath}
  description: Production
  variables:
    basePath:
      default: /sell/account/v1
tags:
- name: Deal_item
paths:
  /deal_item:
    get:
      tags:
      - Deal_item
      description: 'This method retrieves a paginated set of deal items. The result set contains all deal items associated with the specified search criteria and marketplace ID.<h3>Restrictions</h3>This method can return a maximum of 10,000 items. For a list of supported sites and other restrictions, see <a href="/api-docs/buy/browse/overview.html#API" target="_blank">API Restrictions</a>.<br><br><span class="tablenote"><b>eBay Partner Network: </b> In order to receive a commission for your sales, you must use the URL returned in the <code>itemAffiliateWebUrl</code> field to forward your buyer to the ebay.com site.</span>'
      operationId: getDealItems
      parameters:
      - name: category_ids
        in: query
        description: This query parameter specifies the unique identifier of the eBay category for the search.<br><br>For details see <a href="/api-docs/buy/buy-categories.html" target="_blank">Get Categories for Buy APIs</a>.
        required: false
        schema:
          type: string
      - name: commissionable
        in: query
        description: This query parameter allows the response to filter by commissionable items.<br><br>If set to <code>true</code>, only commissionable items will be returned in the response. If set to <code>false</code>, commissionable items will <b>not</b> be returned in the response.<br><br><span class="tablenote"><b>Note:</b> This filter is currently only supported for the US marketplace.</span>
        required: false
        schema:
          type: string
      - name: delivery_country
        in: query
        description: This query parameter allows the response to only return items that can be shipped to the specified country (2-digit ISO code).
        required: false
        schema:
          type: string
      - name: limit
        in: query
        description: The maximum number of items, from the current result set, returned on a single page.
        required: false
        schema:
          type: string
      - name: offset
        in: query
        description: The number of items that will be skipped in the result set. This is used with the <b>limit</b> field to control the pagination of the output.<br /><br />For example, if the <b>offset</b> is set to <code>0</code> and the <b>limit</b> is set to <code>10</code>, the method will retrieve items 1 through 10 from the list of items returned. If the <b>offset</b> is set to <code>10</code> and the <b>limit</b> is set to <code>10</code>, the method will retrieve items 11 through 20 from the list of items returned.<br /><br /><b>Default:</b> <code>0</code>
        required: false
        schema:
          type: string
      - name: X-EBAY-C-MARKETPLACE-ID
        in: header
        description: This header identifies the eBay marketplace.<br><br>See <a href="/api-docs/static/rest-request-components.html#marketpl " target="_blank ">HTTP request headers</a> for supported marketplace ID values.
        required: true
        schema:
          type: string
      - name: X-EBAY-C-ENDUSERCTX
        in: header
        description: This header is required to support revenue sharing for eBay Partner Network and to improve the accuracy of shipping and delivery time estimations.<br><br>For additional information, refer to <a href="/api-docs/buy/static/api-browse.html#Headers" target="_blank ">Use request headers</a> section of the Buying Integration Guide.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DealItemSearchResponse'
        '400':
          description: Bad Request
          x-response-codes:
            errors:
              '180001':
                domain: API_DEAL
                category: REQUEST
                description: Invalid, missing or unsupported marketplace. Please refer to documentation.
              '180002':
                domain: API_DEAL
                category: REQUEST
                description: The specified limit is invalid. Maximum value supported is 100.
              '180003':
                domain: API_DEAL
                category: REQUEST
                description: The specified offset is invalid.
              '180005':
                domain: API_DEAL
                category: REQUEST
                description: category_ids length exceeded. Please check documentation for maximum values supported.
              '180007':
                domain: API_DEAL
                category: REQUEST
                description: Invalid or unsupported filter 'commissionable' for the requested marketplace. Please refer to documentation.
              '180010':
                domain: API_DEAL
                category: REQUEST
                description: Invalid filter for 'delivery_country'. Please refer to the documentation for supported values.
        '403':
          description: Forbidden
          x-response-codes:
            errors:
              '180009':
                domain: API_DEAL
                category: REQUEST
                description: Not authorized. Please contact developer support for assistance.
        '500':
          description: Internal Server Error
          x-response-codes:
            errors:
              '180000':
                domain: API_DEAL
                category: APPLICATION
                description: There was a problem with an eBay internal system or process. Contact eBay developer support for assistance.
      security:
      - api_auth:
        - https://api.ebay.com/oauth/api_scope/buy.deal
components:
  schemas:
    Image:
      type: object
      properties:
        height:
          type: string
          description: The height of the image.
        imageUrl:
          type: string
          description: The relative path to the image location.
        text:
          type: string
          description: The text associated with the image.
        width:
          type: string
          description: The width of the image.
      description: The type that defines the details of an image, such as size and URL.
    ShippingOption:
      type: object
      properties:
        shippingCost:
          description: 'The final shipping cost for all items after all discounts are applied. <br /><br /><span class="tablenote"><b> Note: </b>The price does include the value-added tax (VAT) for applicable jurisdictions when requested from supported marketplaces. In this case, users must pass the <a href="/api-docs/static/rest-request-components.html#HTTP"><code>X-EBAY-C-MARKETPLACE-ID</code></a> request header specifying the supported marketplace (such as <code>EBAY_GB</code>) to see the VAT-inclusive pricing. For more information on VAT, refer to <a href="https://www.ebay.co.uk/help/listings/default/vat-obligations-eu?id=4650&st=12&pos=1&query=Your%20VAT%20obligations%20in%20the%20EU&intent=VAT">VAT Obligations in the EU</a>.</span>'
          $ref: '#/components/schemas/Amount'
        shippingCostType:
          type: string
          description: 'The class of the shipping cost. <br /><br /><b> Valid Values: </b> <code>FIXED</code> or <code>CALCULATED</code> <br /><br />Code so that your app gracefully handles any future changes to this list. '
      description: The details provided for the shipping provider, such as shipping cost and type.
    Amount:
      type: object
      properties:
        currency:
          type: string
          description: The three-letter <a href="https://www.iso.org/iso-4217-currency-codes.html" target="_blank">ISO 4217</a> code representing the currency of the amount in the <b> value</b> field.<br /><br /><b> Default:</b> The currency of the authenticated user's country. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/buy/deal/types/bas:CurrencyCodeEnum'>eBay API documentation</a>
        value:
          type: string
          description: The monetary value, in the currency specified by the <b> currency</b> field.
      description: The currency and value of the item.
    DealItemSearchResponse:
      type: object
      properties:
        dealItems:
          type: array
          description: A list of deal items that match the search criteria.
          items:
            $ref: '#/components/schemas/DealItem'
        href:
          type: string
          description: The relative path to the current set of results.
        limit:
          type: integer
          description: The maximum number of items, from the current result set, returned on a single page.<br /><br /><b>Default:</b> <code>20</code>
          format: int32
        next:
          type: string
          description: The relative path to the next set of results.
        offset:
          type: integer
          description: The number of items that will be skipped in the result set. This is used with the <b>limit</b> field to control the pagination of the output.<br /><br />For example, if the <b>offset</b> is set to <code>0</code> and the <b>limit</b> is set to <code>10</code>, the method will retrieve items 1 through 10 from the list of items returned. If the <b>offset</b> is set to <code>10</code> and the <b>limit</b> is set to <code>10</code>, the method will retrieve items 11 through 20 from the list of items returned.<br /><br /><b>Default:</b> <code>0</code>
          format: int32
        prev:
          type: string
          description: The relative path to the previous set of results.
        total:
          type: integer
          description: The total number of matches for the search criteria.
          format: int32
      description: The result set for the deal item search.
    MarketingPrice:
      type: object
      properties:
        discountAmount:
          description: The monetary value of the seller discount.
          $ref: '#/components/schemas/Amount'
        discountPercentage:
          type: string
          description: The percentage of the seller discount based on the value returned in the <b>originalPrice</b> field.
        originalPrice:
          description: The monetary value of the item prior to the discount.
          $ref: '#/components/schemas/Amount'
        priceTreatment:
          type: string
          description: 'The pricing treatment (discount) that was applied to the price of the item. <br /><br /><span class="tablenote"><b>Note: </b> The pricing treatment affects how and where the discounted price can be displayed.</span> For implementation help, refer to <a href=''https://developer.ebay.com/api-docs/buy/deal/types/api:PriceTreatmentEnum''>eBay API documentation</a>'
      description: A type that describes the seller discount.
    DealItem:
      type: object
      properties:
        additionalImages:
          type: array
          description: The additional images for the deal item.
          items:
            $ref: '#/components/schemas/Image'
        categoryAncestorIds:
          type: array
          description: The IDs of the ancestors for the primary category.
          items:
            type: string
        categoryId:
          type: string
          description: The ID of the leaf category for the deal item. A leaf category is the lowest level in a category and has no children.
        commissionable:
          type: boolean
          description: A boolean value specifying whether the listing has commission.
        dealAffiliateWebUrl:
          type: string
          description: The deal associated with the item with affiliate attribution.
        dealEndDate:
          type: string
          description: The date after which the deal ends.
        dealStartDate:
          type: string
          description: The date on which the deal starts.
        dealWebUrl:
          type: string
          description: The web URL for the deal associated with the item.
        energyEfficiencyClass:
          type: string
          description: A string value specifying the Energy Efficiency class.
        image:
          description: The primary image for the deal item.
          $ref: '#/components/schemas/Image'
        itemAffiliateWebUrl:
          type: string
          description: The item web URL with affiliate attribution.
        itemGroupId:
          type: string
          description: 'The unique identifier for the deal item group. This is the parent item ID for the seller-defined variations.<br /><br /><span class="tablenote"><b>Note: </b>This field is returned for multiple-SKU items.</span>'
        itemGroupType:
          type: string
          description: An enumeration value that indicates the type of item group. An item group contains items that have various aspect differences, such as color, size, or storage capacity. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/buy/deal/types/api:ItemGroupTypeEnum'>eBay API documentation</a>
        itemId:
          type: string
          description: 'The unique identifier for the deal item.<br /><br /><span class="tablenote"><b>Note: </b>This field is only returned for single-SKU items.</span>'
        itemWebUrl:
          type: string
          description: The web URL for the deal item.
        legacyItemId:
          type: string
          description: The legacy item ID associated with the deal item.
        marketingPrice:
          description: The original price for the deal item, and the discount amount and percentage.
          $ref: '#/components/schemas/MarketingPrice'
        price:
          description: 'The price for the deal item. <br /><br /><span class="tablenote"><b> Note: </b>The price does include the value-added tax (VAT) for applicable jurisdictions when requested from supported marketplaces. In this case, users must pass the <a href="/api-docs/static/rest-request-components.html#HTTP"><code>X-EBAY-C-MARKETPLACE-ID</code></a> request header specifying the supported marketplace (such as <code>EBAY_GB</code>) to see the VAT-inclusive pricing. For more information on VAT, refer to <a href="https://www.ebay.co.uk/help/listings/default/vat-obligations-eu?id=4650&st=12&pos=1&query=Your%20VAT%20obligations%20in%20the%20EU&intent=VAT">VAT Obligations in the EU</a>.</span>'
          $ref: '#/components/schemas/Amount'
        qualifiedPrograms:
          type: array
          description: A list of programs applicable to the item.
          items:
            type: string
            description: ' For implementation help, refer to <a href=''https://developer.ebay.com/api-docs/buy/deal/types/api:ProgramEnum''>eBay API documentation</a>'
        shippingOptions:
          type: array
          description: The cost required to ship the deal item.
          items:
            $ref: '#/components/schemas/ShippingOption'
        title:
          type: string
          description: The title of the deal item.
        unitPrice:
          description: 'The price per unit for the deal item. Some European countries require listings for certain types of products to include the price per unit so that buyers can accurately compare prices. <br /><br />For example: <br /><br /><code>"unitPricingMeasure": "100g",<br /> "unitPrice": {<br />&nbsp;&nbsp;"value": "7.99",<br />&nbsp;&nbsp;"currency": "GBP"</code>'
          $ref: '#/components/schemas/Amount'
        unitPricingMeasure:
          type: string
          description: 'The designation used to specify the quantity of the deal item, such as size, weight, volume, and count. This helps buyers compare prices. <br /><br />For example, the following tells the buyer that the item is 7.99 per 100 grams. <br /><br /><code>"unitPricingMeasure": "100g",<br /> "unitPrice": {<br />&nbsp;&nbsp;"value": "7.99",<br />&nbsp;&nbsp;"currency": "GBP"</code>'
      description: The detailed data returned for the deal item.
  securitySchemes:
    api_auth:
      type: oauth2
      description: The security definitions for this API. Please check individual operations for applicable scopes.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.ebay.com/oauth2/authorize
          tokenUrl: https://api.ebay.com/identity/v1/oauth2/token
          scopes:
            https://api.ebay.com/oauth/api_scope/sell.account.readonly: View your account settings
            https://api.ebay.com/oauth/api_scope/sell.account: View and manage your account settings
